-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 18:06:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ateneaapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ateneaapp` ;

-- -----------------------------------------------------
-- Schema ateneaapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ateneaapp` DEFAULT CHARACTER SET utf8 ;
USE `ateneaapp` ;

-- -----------------------------------------------------
-- Table `ateneaapp`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`categories` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`levels` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`questions` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `categories_id` INT NOT NULL,
  `levels_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`options` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(60) NOT NULL,
  `correct` TINYINT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`entities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`entities` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`entities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`users` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `entities_id` INT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`wildcards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`wildcards` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`wildcards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `active` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`match_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`match_states` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`match_states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`matches` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `match_states_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`matches_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`matches_answers` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`matches_answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number_question` INT NULL,
  `questions_id` INT NOT NULL,
  `options_id` INT NULL,
  `matches_id` INT NOT NULL,
  `wildcards_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`token_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`token_states` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`token_states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ateneaapp`.`users_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ateneaapp`.`users_token` ;

CREATE TABLE IF NOT EXISTS `ateneaapp`.`users_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `token_states_id` INT NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
